### ISSUE TITLE
Final project Datasets

### ISSUE THREAD

**Issue by nadavWeisler** [nadavWeisler/MeaningAndComputation#1]
https://www.kaggle.com/michaelarman/poemsdataset

https://www.kaggle.com/anjaneyatripathi/emotion-classification-nlp

https://www.kaggle.com/columbine/imdb-dataset-sentiment-analysis-in-csv-format

https://www.kaggle.com/rmisra/news-headlines-dataset-for-sarcasm-detection

https://www.kaggle.com/imoore/60k-stack-overflow-questions-with-quality-rate

https://www.kaggle.com/andrewmvd/okcupid-profiles

**Comment by yanirelfasy** [comment]
https://www.kaggle.com/mukulkirti/positive-and-negative-word-listrar

**Comment by nadavWeisler** [comment]
https://www.kaggle.com/iwilldoit/emotions-sensor-data-set?select=Andbrain_DataSet.csv
https://www.kaggle.com/sankha1998/emotion?select=Emotion%28sad%29.csv
